/**
 * Roche Home Assignment
 */
package com.roche.assignment.commerce.backend.persistence.model;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

import lombok.Getter;

/**
 * Common columns for all entities.
 *
 * @author Neill McQuillin (created by)
 * @since 26 August 2019 (creation date)
 */
@MappedSuperclass
abstract class DummyCommon {
	/**
	 * Primary key generated by database
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(unique = true, nullable = false, precision = 10)
	@Getter
	private Long id;
}