/**
 * Roche Home Assignment
 */
package com.roche.assignment.commerce.backend.persistence.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * ProductDTO entity.
 *
 * @author Neill McQuillin (created by)
 * @since 22 July 2019 (creation date)
 */
@Entity
public class Product implements Serializable {
	private static final long serialVersionUID = 8096668686739777877L;

	/**
	 * Primary key generated by database
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(unique = true, nullable = false, precision = 10)
	private Long id;

	@Getter
	@Column(nullable = false)
	private final Instant createdOn = Instant.now();

	@Version
	@Column(nullable = false)
	private Long revisionNumber;

	@Getter
	@Setter
	@Column(unique = true, nullable = false)
	private String sku;

	@Getter
	@Setter
	private String name;

	@Getter
	@Setter
	private BigDecimal price;

	@Getter
	@Setter
	private Boolean deleted = Boolean.FALSE;

	@Builder
	public Product(String sku, String name, BigDecimal price) {
		this.sku = sku;
		this.name = name;
		this.price = price;
	}
	
	
}
